#!/bin/bash
# Auto-detect and configure MCP for installed CLIs/TUIs/IDEs
# Generated by Synapsis Environment Detection

set -e

SYNAPSIS_DIR="$HOME/.config/synapsis"
MCP_CONFIG_TEMPLATE='{
  "mcpServers": {
    "synapsis": {
      "type": "stdio",
      "command": "synapsis",
      "args": ["mcp"],
      "enabled": true,
      "autoStart": true,
      "config": {
        "project_key": "auto_detected",
        "heartbeat_interval": 30,
        "auto_save_context": true,
        "tools": [
          "memory_add",
          "memory_search",
          "memory_timeline",
          "agent_session_register",
          "agent_heartbeat",
          "agents_active",
          "task_queue_create",
          "task_claim"
        ]
      }
    }
  }
}'

# Known CLIs that support MCP
declare -A MCP_CLIS=(
    ["opencode"]="$HOME/.opencode"
    ["qwen-code"]="$HOME/.qwen"
    ["claude-code"]="$HOME/.claude"
    ["gemini-cli"]="$HOME/.gemini"
    ["cline"]="$HOME/.config/rooveterinaryinc.roo-cline"
    ["kilo-code"]="$HOME/.config/kilocode.kilo-code"
)

echo "🔍 Synapsis MCP Auto-Configuration"
echo "===================================="
echo ""

# Detect installed CLIs
DETECTED_CLIS=()
for cli in "${!MCP_CLIS[@]}"; do
    if command -v "$cli" &> /dev/null || [ -d "${MCP_CLIS[$cli]}" ]; then
        DETECTED_CLIS+=("$cli")
        echo "✅ Detected: $cli"
    fi
done

echo ""
echo "📋 Found ${#DETECTED_CLIS[@]} MCP-compatible CLIs"
echo ""

# Generate MCP config for each detected CLI
for cli in "${DETECTED_CLIS[@]}"; do
    config_dir="${MCP_CLIS[$cli]}"
    config_file=""
    
    case "$cli" in
        "opencode")
            config_file="$config_dir/mcp.json"
            ;;
        "qwen-code")
            config_file="$config_dir/mcp.json"
            ;;
        "claude-code")
            config_file="$config_dir.json"
            ;;
        "gemini-cli")
            config_file="$config_dir/mcp_config.json"
            ;;
        "cline"|"kilo-code")
            config_file="$config_dir/settings/mcp_settings.json"
            ;;
    esac
    
    if [ -n "$config_file" ]; then
        # Create directory if it doesn't exist
        mkdir -p "$(dirname "$config_file")"
        
        # Check if already configured
        if [ -f "$config_file" ] && grep -q "synapsis" "$config_file" 2>/dev/null; then
            echo "⏭️  Skipping $cli (already configured): $config_file"
        else
            echo "📝 Configuring $cli: $config_file"
            echo "$MCP_CONFIG_TEMPLATE" > "$config_file"
            echo "   ✅ Configured!"
        fi
    fi
done

echo ""
echo "🎉 MCP Auto-Configuration Complete!"
echo ""
echo "Next steps:"
echo "1. Restart your CLI/TUI/IDE"
echo "2. The MCP connection will be established automatically"
echo "3. Check connection status with: synapsis agents_active"
echo ""

# Verify connection
if command -v synapsis &> /dev/null; then
    echo "📊 Current Active Agents:"
    synapsis agents_active 2>/dev/null || echo "   (synapsis server not running)"
fi
